### ISSUE TITLE
Test with JSONPatch spec tests

### ISSUE THREAD

**Issue by Dimava** [marcolink/generate-json-patch#13]
There are JSONPatch tests at https://github.com/json-patch/json-patch-tests

You probably should add them to tests (I guess as a dev dependency you import a json file from), just in case

**Comment by marcolink** [comment]
@Dimava It looks like these tests are for tools that apply patches. `generate-json-patch` just generates patches. Not sure what exactly we could test here. 🤔

**Comment by Dimava** [comment]
🤔
You're correct I guess
Can close this issue then
What lib do you use to apply patches btw?


On another matter,
I'm interested in making a benchmark/comparison for jsonpatch libs, probably sometime this year
If you have any recommendations (e.g. difficult cases that caused bugs, bench cases that you've met in huge quantities, maybe some useful interfaces like the fast-json-patch "observer" that clones the whole object so you can easily calc diffs) please do tell
I did make a list on https://github.com/Starcounter-Jack/JSON-Patch/issues/321#issuecomment-2416071672 (maybe I did miss some libs from https://jsonpatch.com/ tho)

**Comment by marcolink** [comment]
@Dimava  I'd be interested in such a benchmark - please keep me posted :) 

I think applying patches is a rather trivial thing to do, as you just set the values at a given path. Said that, I wouldn't expect too much of a difference in performance.

generating patches is a bit different. All the tools have a different feature sets, which also impacts the performance. I think one of the main questions is: how well can it compare arrays :)  

The other thing is (and that's again mostly relevant in context of arrays), how optimized are the patches. There are endless ways to transform an object between 2 states, especially when you want to change multiple array positions with a single patch. 

For this library, my main focus was to optimise for array diffing. This might be specific to my initial use case.
